### ISSUE TITLE
Getting Runtime exception while implementing library

### ISSUE THREAD

**Issue by Kaushal28** [Rajagopalr3/CustomEditText#1]
I've added the give example code in my layout filr, but got following error on runtime: 

03-12 21:38:25.757 9166-9166/kaushal28.challenge E/AndroidRuntime: FATAL EXCEPTION: main
                                                                   Process: kaushal28.challenge, PID: 9166
                                                                   java.lang.RuntimeException: Unable to start activity ComponentInfo{kaushal28.challenge/kaushal28.challenge.signupActivity}: android.view.InflateException: Binary XML file line #0: Binary XML file line #0: Error inflating class com.libIZO.CustomEditText
                                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2665)
                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
                                                                       at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                       at android.os.Looper.loop(Looper.java:154)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
                                                                    Caused by: android.view.InflateException: Binary XML file line #0: Binary XML file line #0: Error inflating class com.libIZO.CustomEditText
                                                                    Caused by: android.view.InflateException: Binary XML file line #0: Error inflating class com.libIZO.CustomEditText
                                                                    Caused by: java.lang.ClassNotFoundException: Didn't find class "com.libIZO.CustomEditText" on path: DexPathList[[zip file "/data/app/kaushal28.challenge-2/base.apk"],nativeLibraryDirectories=[/data/app/kaushal28.challenge-2/lib/x86, /system/lib, /vendor/lib]]
                                                                       at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
                                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                       at android.view.LayoutInflater.createView(LayoutInflater.java:609)
                                                                       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:787)
                                                                       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
                                                                       at android.view.LayoutInflater.rInflate(LayoutInflater.java:858)
                                                                       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
                                                                       at android.view.LayoutInflater.rInflate(LayoutInflater.java:861)
                                                                       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
                                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
                                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
                                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
                                                                       at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287)
                                                                       at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
                                                                       at kaushal28.challenge.signupActivity.onCreate(signupActivity.java:11)
                                                                       at android.app.Activity.performCreate(Activity.java:6679)
                                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
                                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
                                                                       at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                       at android.os.Looper.loop(Looper.java:154)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by Rajagopalr3** [comment]
Download the complete project and take build and install it will work...
or
use this lib in  dependency section compile 'com.libizo:customedittext:1.0.2'


android.view.InflateException: Binary XML file line #0: Binary XML file line #0: Error inflating class com.libIZO.CustomEditText

this exception will come when gradle not sync with library.


still having issue means please give some more details like below

1.Android studio version
2.please share the code to check

**Comment by Kaushal28** [comment]
I've used your class in my project instead of dependency. Now it's working fine. Thanks

**Comment by karique01** [comment]
i had the same problem in a project recently updated from AppCompatActivity v7 to androidx, but after i change the version to:
implementation 'com.libizo:customedittext:1.0.7'
i could compile succesfully
