### ISSUE TITLE
crash when setError and touch for first time

### ISSUE THREAD

**Issue by mehdiyari** [Rajagopalr3/CustomEditText#6]
hi dear friend. 
i have problem with your editText. 

when iam set error to editText and click for first touch app crashed

// this line set error 
viewUserConfirmPasswordHolder.error = reason

stackTrace:
`
java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.drawable.Drawable.getIntrinsicWidth()' on a null object reference
        at com.libizo.CustomEditText$1.onTouch(CustomEditText.java:118)
        at android.view.View.dispatchTouchEvent(View.java:10008)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
        at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:447)
        at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1871)
        at android.app.Activity.dispatchTouchEvent(Activity.java:3213)
        at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:68)
        at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:409)
        at android.view.View.dispatchPointerEvent(View.java:10232)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4856)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4717)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4249)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4302)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4268)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4395)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4276)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4452)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4249)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4302)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4268)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4276)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4249)
        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6676)
        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6650)
        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6611)
        at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6803)
        at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:192)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:356)
        at android.os.Looper.loop(Looper.java:138)
        at android.app.ActivityThread.main(ActivityThread.java:6523)
        at java.lang.reflect.Method.invoke(Native Method)
    	at com.android.internal.
11-30 21:43:29.728 30707-30707/info.flura.flura E/AndroidRuntime: FATAL EXCEPTION: main
    Process: info.flura.flura, PID: 30707
    java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.drawable.Drawable.getIntrinsicWidth()' on a null object reference
        at com.libizo.CustomEditText$1.onTouch(CustomEditText.java:118)
        at android.view.View.dispatchTouchEvent(View.java:10008)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
        at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:447)
        at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1871)
        at android.app.Activity.dispatchTouchEvent(Activity.java:3213)
        at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:68)
        at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:409)
        at android.view.View.dispatchPointerEvent(View.java:10232)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4856)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4717)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4249)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4302)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4268)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4395)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4276)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4452)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4249)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4302)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4268)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4276)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4249)
        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6676)
        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6650)
        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6611)
        at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6803)
        at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:192)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:356)
        at android.os.Looper.loop(Looper.java:138)
11-30 21:43:29.729 30707-30707/info.flura.flura E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:6523)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
`

**Comment by Rajagopalr3** [comment]
which library version are you using?. If you are using 1.0.3 kindly upgrade to 1.0.4. This issue got fixed in latest version

**Comment by mehdiyari** [comment]
thanks man
